spring:
  application:
    name: vg-ms-family

  r2dbc:
    # Conexión a la base de datos Family
    url: ${R2DBC_URL} #r2dbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres
    username: ${R2DBC_USERNAME} #postgres.hjazvqbxrkrjvcmznljy
    password: ${R2DBC_PASSWORD} #npg_jnBdH2M7gwJz
    pool:
      max-size: 20
      min-size: 5
      validation-query: SELECT 1

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS} #pkc-619z3.us-east1.gcp.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
        #sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="QPOHIHRZOG4ZZJZ5" password="obWMF0fhB+HKXKUvFz3YvBw2p5qZuubgJN5wZSuz750hjaSD9SLW6fFOcZq4u/lp";
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/security-prs1

  sql:
    init:
      mode: always
      timeout: 10s

  logging:
    level:
      io.r2dbc: DEBUG
      org.springframework.r2dbc: DEBUG
      org.springframework.kafka: DEBUG

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

# Housing service configuration
housing:
  service:
    url: ${HOUSING_SERVICE_URL}
